# Generated by Django 6.0.1 on 2026-01-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='usuario_postou',
        ),
    ]
